server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/giann02/config-server-firstTime
          default-label: main
          force-pull: true